### ISSUE TITLE
jQuery UI assets missing in production

### ISSUE THREAD

**Issue by dachinat** [opoloo/lines-engine#19]
In a fresh install, in production I get

<img width="589" alt="screen shot 2017-11-28 at 11 05 01 am" src="https://user-images.githubusercontent.com/22872749/33306484-332fc0d4-d42c-11e7-922a-3315858997c1.png">

Ruby version: 2.4.2p198
Rails version: Rails 5.1.4

**Comment by thej** [comment]
Fixed in latest version (>=1.2.5)
