### ISSUE TITLE
Help Installing

### ISSUE THREAD

**Issue by TuskerIT** [opoloo/lines-engine#26]
Hi all installed after some modding and adding [4.2] to all of the migrate tasks.

Now if i go to localhost:3000/blog I get stylesheet errors. It appears variables are missing like $max-width? Where are these set?

**Comment by occorom** [comment]
I have the same issues, did you manage to find a solution ?

**Comment by yickting** [comment]
https://github.com/opoloo/lines-engine/issues/11

**Comment by thej** [comment]
Duplicate of #11
