### ISSUE TITLE
Failed to upload painting: Article must exist

### ISSUE THREAD

**Issue by yickting** [opoloo/lines-engine#27]
Anyone encounter this issue as well while trying to upload images in blog post?

Would appreciate some help in fixing it.

Cheers.

**Comment by BenoitDK** [comment]
I am running into the same problem...

**Comment by yickting** [comment]
Thank you for sharing the solution!

But i only see this: ![image alt text](image url)

Could you share again?

Cheers

**Comment by BenoitDK** [comment]
yes just put ![image alt text](image url) in your article with the url of your image

**Comment by yickting** [comment]
oh sorry, my vision was blurred just now, I thought I saw was some failed screenshot upload error, will give it a try, thanks !!

**Comment by ViTVetal** [comment]
Same problem

**Comment by hanhdt** [comment]
This is happened when you guys are using Rails 5.*

Look at `models/lines/picture.rb` on `belongs_to :article, touch: true`. From Rails 5, `belongs_to` is required by default. In this case, you haven't `article` persisted yet. Therefore, you got the validation error message like above.

A workaround is updating codes by yourself.
Change  `belongs_to :article, touch: true` to `belongs_to :article, touch: true, optional: true` in the `picture` model.

**Comment by thej** [comment]
Fixed in latest release (1.2.6)
