### ISSUE TITLE
Unmaintained? Use my fork

### ISSUE THREAD

**Issue by adonespitogo** [opoloo/lines-engine#29]
Maintainers of this repo seem to be unresponsive.

An updated version of this repository is in my [github account](https://github.com/adonespitogo/lines-engine).

It contains pending pull requests from this repo and some bug fixes and ability to specify carrierwave storage. Works with Rails 5.2

Opoloo: Please let me know if you need maintainer for this project.

**Comment by thej** [comment]
Thanks for the support @adonespitogo ! 

A new version will be release today :)

**Comment by adonespitogo** [comment]
@thej Thanks! Looking forward to the new release. Wonder if you could include my commits in my fork, though I can make another PR if need be. It contains additional features and some minor bug fixes in views and controllers related to namespaced models.

New features include:

- Ability to use ERB syntax for `lines_config.yml`
- Specify carrierwave storage

**Comment by adonespitogo** [comment]
See [changelogs](https://github.com/adonespitogo/lines-engine/blob/master/CHANGELOG.md)
