### ISSUE TITLE
hellooo

### ISSUE THREAD

**Issue by itsandrewk** [opoloo/lines-engine#3]
i'm trying to integrate this blog onto a page of my rails application,

ive tried using different yields, renders

is this possible even?

**Comment by thej** [comment]
Yes, you can. Essentially, you have to code the required controller logic to make the articles available to your action.

Simply add the following line to your coontroller action:

``` ruby
@articles = Lines::Article.published
```

Now you can iterate through the `@articles` array in your corresponding view to access each published article.

Hope I could help.

**Comment by itsandrewk** [comment]
!!!!! awesome can't wait to try
