### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by colinstrachan** [opoloo/lines-engine#37]
Hey guys, I really love this gem. However I have this strange issue on one of my blogs where my images go blank around 12 to 24 hours after I uploaded them. So I create a blog, attach images and publish it. It's fine for a while. But then when I check it the following night, the images don't work anymore. It's only happening with one of my articles, not the other. Any idea how I can fix this or what I might be doing wrong? My blog is at www.strachanmusic.com/blog - thank you!

**Comment by adonespitogo** [comment]
Did you check your hosting account restrictions?

**Comment by colinstrachan** [comment]
Thanks for the response! What should I look for exactly?
I'm using Heroku. It's just odd that doesn't happen for the first article I uploaded.

**Comment by adonespitogo** [comment]
Heroku does not let you [store files on the webserver](https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted). You need to use external services like AWS S3. You can look for tutorials on how to do that.

**Comment by colinstrachan** [comment]
Perfect, I will. Thanks for your help.
